### ISSUE TITLE
Technical details missing

### ISSUE THREAD

**Issue by s09bQ5** [masksshow/Thinkpad-E14-15-AMD-Gen-2-FIX#2]
On the Lenovo forum you wrote that this is not BIOS bug. How did you come to that conclusion?

It looks like setting H8DR to One switches the DSDT into a mode where it will not use the embedded controller to perform certain tasks. Is there anything missing in Linux to communicate correctly with the EC?

Or is it that the _REG method of EC0 should have set H8DR to One but didn't for some reason?

Hmm... ec_install_handlers from drivers/acpi/ec.c does call acpi_install_address_space_handler which should evaluate the _REG method with ACPI_ADR_SPACE_EC and ACPI_REG_CONNECT...

**Comment by masksshow** [comment]
I read that disabling the kernel module helps, and I thought it was not a BIOS.
https://unix.stackexchange.com/questions/602355/thinkpad-fn-keys-only-working-after-suspend
But I didn't check it.

But all functions work the same as after sleep.

**Comment by s09bQ5** [comment]
But then how did you go from blacklisting thinkpad_acpi to forcing EC support in DSDT to on?

And I have to correct myself. Setting H8DR to 1 switches the DSDT into a mode where it will directly use the embedded controller through a memory mapped region to perform certain tasks. When it is set to 0, the DSDT writes a command to RAM and triggers an SMI using port 0xB2. The actual ACPI_ADR_SPACE_EC region is rarely used - only for signalling suspend to disk and for waiting for completion of something in the MHPF method of the HKEY LEN0268 device.

**Comment by masksshow** [comment]
The DSDT feature in Tinkypad is by far the most popular.
https://www.spinics.net/lists/linux-acpi/msg51999.html
I looked at the DSDT table and initializing H8DR with "One" instead of "Zero" fixes this problem, I don't know what to do next. You know more than me.

Even if this is a problem with the BIOS, Lenovo wrote, since it works on Windows, it does not need repairs.

What functions do not work after the fix, what is wrong?


The system also uses the clock source: hpet
https://forums.lenovo.com/t5/Other-Linux-Discussions/Clocksource-falling-back-to-HPET-bec-TSC-is-unstable-ThinkPad-E14-Gen-2-maybe-others/m-p/5036464
